# Generated by Django 6.1.1 on 2026-10-05 01:46

import django.contrib.postgres.indexes
import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('base_url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('timeout_ms', models.PositiveIntegerField(default=8000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProviderToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('obtained_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='providers.provider')),
            ],
        ),
        migrations.CreateModel(
            name='RawProviderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('content_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('fetch_count', models.PositiveIntegerField(default=1)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_products', to='providers.provider')),
            ],
            options={
                'db_table': 'raw_provider_product',
                'indexes': [models.Index(fields=['last_seen_at'], name='raw_pp_last_seen_idx'), django.contrib.postgres.indexes.GinIndex(fields=['payload'], name='raw_pp_payload_gin')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='raw_pp_provider_external_uniq')],
            },
        ),
    ]
