# Generated by Django 6.1.1 on 2026-10-05 00:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True, verbose_name='folio')),
                ('client_name', models.CharField(max_length=255, verbose_name='razón social del cliente')),
                ('client_rfc', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='RFC inválido: formato oficial (12-13 caracteres, mayúsculas, sin guiones).', regex='^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$')], verbose_name='RFC del cliente')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='correo del cliente')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de emisión')),
                ('valid_days', models.PositiveSmallIntegerField(default=15, verbose_name='días de vigencia')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitida'), ('SENT', 'Enviada'), ('ACCEPTED', 'Aceptada')], default='DRAFT', max_length=10, verbose_name='estatus')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.16'), max_digits=5, verbose_name='tasa de IVA')),
                ('notes', models.TextField(blank=True, verbose_name='notas / condiciones comerciales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to=settings.AUTH_USER_MODEL, verbose_name='asesor técnico')),
            ],
            options={
                'verbose_name': 'cotización',
                'verbose_name_plural': 'cotizaciones',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='descripción de la partida')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='precio unitario')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='catalog.product', verbose_name='producto')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote', verbose_name='cotización')),
            ],
            options={
                'verbose_name': 'partida',
                'verbose_name_plural': 'partidas',
                'ordering': ['id'],
            },
        ),
    ]
