# Generated by Django 6.1.1 on 2026-10-05 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_sinonimored'),
        ('providers', '0002_alter_rawproviderproduct_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='provider',
            field=models.OneToOneField(blank=True, help_text='Solo si este distribuidor se consulta por API (apps.providers).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier', to='providers.provider', verbose_name='proveedor con API'),
        ),
    ]
